# Generated by Django 4.1.3 on 2022-11-30 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tablas', '0002_pedido_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre',
            new_name='nombre_p',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tablas.cliente'),
        ),
    ]
